### PR TITLE
Update show_QR

### PR DESCRIPTION
**Pull request by caternuson**
Just an idea for #30

### CODE REVIEW

**Comment by ladyada** [comment]
ill take anything cause current code isnt working at all :D

**Comment by caternuson** [comment]
Sure. Was this suppose to be any fancier than just "clear screen and show QR code"?

**Comment by ladyada** [comment]
its pretty simple, yeah

**Comment by caternuson** [comment]
Generally works. This:
```python
Adafruit CircuitPython 4.0.0-rc.1 on 2019-04-23; Adafruit PyPortal with samd51j20
>>> from adafruit_pyportal import PyPortal
>>> pp = PyPortal()
ESP firmware: bytearray(b'1.2.2\x00')
Set background to  0
No SD card found: no SD card
>>> pp.show_QR(b'hello world', 8, 20, 20)
```
gives this:
qr_pyportal
which was tested here:
https://zxing.org/w/decode.jspx
and spit back expected result:
qr_test

Note weird border quirk might be related to this:
https://github.com/adafruit/circuitpython/issues/1839

**Comment by ladyada** [comment]
fine by me!

**Comment by caternuson** [comment]
@ladyada want me to version bump this?

**Comment by ladyada** [comment]
yes plz!

**Comment by caternuson** [comment]
Done! Bumped major ver since the function call changed.

**Comment by ladyada** [comment]
amazing, thank you thank you carter :)

**Pull request merged**
