### PR TITLE
Refactored PyPortal to use PortalBase

### PR DESCRIPTION
**Pull request by makermelissa**
This requires https://github.com/adafruit/Adafruit_CircuitPython_PortalBase/pull/8 to work. Making a draft for the moment until I can do some more thorough testing.

### CODE REVIEW

**Review by FoamyGuy — COMMENTED** [review]
I tested this successfully with the simpletest, as well as "PyPortal User Interface" and "PyPortal Bitcoin" learn guide projects. Everything working well on all of those.

On the [Cleveland art photo](https://learn.adafruit.com/cleveland-museum-of-art-pyportal-frame/overview) learn project I did find an error using this version of the library though:
```
Traceback (most recent call last):
  File "code.py", line 32, in <module>
  File "/lib/adafruit_pyportal/__init__.py", line 149, in __init__
AttributeError: 'PyPortal' object has no attribute '_debug'
```
Looks like a good start to the refactor to me.Thanks for working on this!

**Comment by makermelissa** [comment]
Thanks for finding that @FoamyGuy.

**Comment by makermelissa** [comment]
I've been running the weather demo on my PyPortal over the weekend without issues.

**Comment by makermelissa** [comment]
Ok, I feel good about this PR. It will continue to fail checks until https://github.com/adafruit/Adafruit_CircuitPython_PortalBase/pull/8 is merged in and released.

**Review by FoamyGuy — APPROVED** [review]
I re-tested those PyPortal projects and everything is working well now.

Changes look good to me.

**Pull request merged**
