### PR TITLE
Update adafruit_pyportal.py

### PR DESCRIPTION
**Pull request by DigitalMakerCIC**
Added ability to pass headers for authentication typically used by Azure API's

### CODE REVIEW

**Comment by ladyada** [comment]
nice!

**Comment by lemonkey** [comment]
I had a similar requirement where I needed to be able to pass a basic authorization header for my image URL. 

Is the format of the headers parameter expecting something like the following?

```HEADERS = {"Authorization":"Basic <some token>"}```

And do you know if these headers are also used when the image formatter service ultimately calls the image URL to fetch the image and then process it?

Instead of using a data source and image JSON path, I'm using the newer image_url_path property for the image URL.

An update to the example code would be appreciated.

**Comment by DigitalMakerCIC** [comment]
Hi Details are here in this blog post https://digital-maker.co.uk/adafruit-pyportal-uk-tide-viewer

**Comment by lemonkey** [comment]
@DigitalMakerCIC Great thanks for the link!

**Pull request merged**
